r"""Parameter count: the Standard Model vs the Eternal Dawn particle sector.

The claim (conditional on the programme delivering -- 'banking on S' and the lattice
targets): because the forces and masses are tied to the gravity-torsion field, the SM's
free parameters become DERIVED, not inserted. This module tabulates the count honestly.

The Standard Model has ~19 free parameters (no neutrino mass) to ~26 (with neutrinos):
3 gauge couplings, 2 Higgs (v, m_H), 9 charged-fermion masses, 4 CKM, 1 theta_QCD,
(+ 7 neutrino). Every fermion mass and mixing is inserted by hand (the Yukawa sprinkling).

In the ED particle sector, IF the programme delivers, each of these traces to the
framework's existing base constants (G, hbar, c) plus ONE dynamically-generated scale
(the condensate v=f_pi, set by dimensional transmutation of the torsion coupling -- not a
free parameter). Status is kept per line: 'derived' (structure shown, number owed to
lattice), 'forced' (fixed by the label/algebra), or 'owed'.
"""

from __future__ import annotations

# (name, count) for the Standard Model free parameters
SM_PARAMETERS = [
    ("gauge couplings (g1,g2,g3)", 3),
    ("Higgs sector (v, m_H)", 2),
    ("charged-fermion masses (6 quarks + 3 leptons)", 9),
    ("CKM mixing (3 angles + 1 phase)", 4),
    ("theta_QCD (strong CP)", 1),
    ("neutrino masses + PMNS mixing", 7),
]

# (name, SM_count_replaced, ED_status) -- how ED accounts for each block
ED_ACCOUNTING = [
    ("gauge couplings", 3, "derived: strong colour forced by the label; the one torsion "
     "four-fermion coupling (Fierz G_A=G_V) sets the resonance/walking structure; "
     "couplings trace to G via the connection"),
    ("Higgs sector", 2, "derived: composite (no elementary Higgs); the scale v=f_pi is "
     "dynamically generated by dimensional transmutation of G -- not a free parameter"),
    ("9 fermion masses", 9, "derived (number owed): masses are wavefunction OVERLAP "
     "integrals (Yukawa-as-overlap); the geometric ladder is shown, exact ratios owed to "
     "lattice"),
    ("4 CKM mixings", 4, "derived (owed): mixings are overlaps between soliton generations"),
    ("theta_QCD", 1, "owed: strong CP not yet addressed -- an honest residual"),
    ("7 neutrino params", 7, "derived (owed): same overlap mechanism, plus the CPT-mirror "
     "structure of Part I"),
]


def sm_count(with_neutrinos=True):
    """Total SM free parameters (~26 with neutrinos, ~19 without)."""
    return sum(c for name, c in SM_PARAMETERS
               if with_neutrinos or "neutrino" not in name)


def ed_base_constants():
    """The base dimensionful constants the ED particle sector inherits (NOT new to it --
    shared with Part I and all of physics): G, hbar, c. The condensate scale is generated
    from these by dimensional transmutation, so it is not an additional input."""
    return ["G", "hbar", "c"]


def ed_new_free_parameters_ideal():
    """In the ideal (fully delivered) case, the ED particle sector adds ZERO new
    fundamental free parameters: every SM parameter becomes a consequence of G, hbar, c
    and the dynamically-generated condensate scale."""
    return 0


def ed_honest_residuals():
    """Honest residual inputs/choices not yet derived (the gap between promise and proof)."""
    return [
        "the gauge group / number of colours (3 forced as the Pauli minimum; 4 a "
        "speculative Pati-Salam option)",
        "theta_QCD (strong CP) -- not yet addressed",
        "and -- the load-bearing caveat -- the NUMBERS (S<0.1, exact masses, confinement) "
        "are owed to lattice; the structure supports zero new parameters, the proof does not "
        "yet exist",
    ]


def replaced_count():
    """How many SM parameters the programme aims to derive (all of them)."""
    return sum(c for _, c, _ in ED_ACCOUNTING)
