#!/usr/bin/env python3
r"""The Weltformel spectrum in physical units: all 15 elementary masses, no fitting.

Computes the 12 fermion masses (+ W, Z, Higgs) purely from the equations of Part~II and the
natural constants, with a SINGLE global scale (the condensate; the top sets it) and NO per-tower
or per-particle fitting -- the honest ab-initio result. Emits:
  * chapters/auto/weltformel_table.tex -- all 15, torsiton mass with the measured value in ();
  * figures/pdf/weltformel_spectrum.pdf -- a log plot, theory (open) vs measured (filled),
    coloured by family, the 15 particles across twelve orders of magnitude.
Structure exact; absolute values within one to two orders (no fit); bosons within a percent.
"""
from __future__ import annotations

import os

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

from cartasis_sims import weltformel as wf

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
PDF_DIR = os.path.join(ROOT, "figures", "pdf")
TEX_DIR = os.path.join(ROOT, "chapters", "auto")
OUT_DIR = os.path.join(ROOT, "sims", "output")
for d in (PDF_DIR, TEX_DIR, OUT_DIR):
    os.makedirs(d, exist_ok=True)

GROUP_COLOR = {"up-quark": "C3", "down-quark": "C2", "charged-lepton": "C0", "neutrino": "C4"}
GROUP_LABEL = {"up-quark": "up-type quarks", "down-quark": "down-type quarks",
               "charged-lepton": "charged leptons", "neutrino": "neutrinos"}


def _u(m_gev):
    """Pretty mass (input GeV) as TeV/GeV/MeV/keV/eV."""
    if m_gev <= 0:
        return r"\to 0"
    m = m_gev * 1000.0  # MeV
    if m >= 1e6:
        return f"{m/1e6:.3g}~\\mathrm{{TeV}}"
    if m >= 1000:
        return f"{m/1000:.3g}~\\mathrm{{GeV}}"
    if m >= 1:
        return f"{m:.3g}~\\mathrm{{MeV}}"
    if m >= 1e-3:
        return f"{m*1000:.3g}~\\mathrm{{keV}}"
    return f"{m*1e6:.2g}~\\mathrm{{eV}}"


def main():
    mat = wf.fermion_matrix()
    bm = wf.bosons()
    res = wf.residual_factors()

    # ---------- table ----------
    lines = [r"% auto-generated by figures/scripts/draft_weltformel_spectrum.py",
             r"\begin{table}[t]", r"  \centering",
             r"  \caption{The Weltformel spectrum: all fifteen elementary masses computed from"
             r" the equations of Part~II and the natural constants, with a \emph{single} global"
             r" scale (the condensate, fixed by the top) and \emph{no} per-particle fitting. Each"
             r" entry is the torsiton prediction with the measured value in parentheses. The"
             r" structure is exact---three generations, geometric ladders, quarks above leptons,"
             r" the neutrino seesaw-suppressed; the absolute fermion values are within one to two"
             r" orders of magnitude (the inter-tower splittings are owed to the lattice,"
             r" Appendix~\ref{app:lattice}), and the gauge bosons land within a percent.}",
             r"  \label{tab:weltformel}",
             r"  \begin{tabular}{l l l l}", r"    \toprule",
             r"    family & \multicolumn{3}{c}{generation: torsiton (measured)} \\",
             r"     & I & II & III \\", r"    \cmidrule(lr){2-4}"]
    for t in ("up-quark", "down-quark", "charged-lepton", "neutrino"):
        if t == "neutrino":
            cells = [f"$0^{{\\dagger}}$ (${_u(o)}$)" for o in wf.OBSERVED_GEV[t]]
        else:
            cells = [f"${_u(p)}$ (${_u(o)}$)" for p, o in zip(mat[t], wf.OBSERVED_GEV[t])]
        lines.append(f"    {GROUP_LABEL[t]} & " + " & ".join(cells) + r" \\")
    lines += [r"    \multicolumn{4}{l}{\footnotesize $^{\dagger}$ the leading Dirac mass"
              r" vanishes (the right-handed neutrino is a total singlet); the physical mass is"
              r" the sub-eV seesaw floor $m_\nu\sim m_D^2/M$ ($M$ owed).} \\"]
    lines += [r"    \midrule",
              r"    gauge / scalar bosons & "
              f"$W$: ${_u(bm['W'])}$ (${_u(wf.OBSERVED_BOSONS['W'])}$) & "
              f"$Z$: ${_u(bm['Z'])}$ (${_u(wf.OBSERVED_BOSONS['Z'])}$) & "
              f"$H$: ${_u(bm['H'])}$ (${_u(wf.OBSERVED_BOSONS['H'])}$) \\\\",
              r"    \midrule",
              r"    \multicolumn{4}{l}{\emph{predicted composite (torsiton-pair) family --"
              r" the Higgs is the lightest member:}} \\"]
    # the resonances above the Higgs, asterisked as not-yet-observed
    sym = {"heavier scalar": "h'", "vector (techni-rho)": r"\rho_T",
           "axial-vector (techni-a_1)": "a_T"}
    fam = [r for r in wf.composite_resonances() if not r[3]]
    cells = [f"${sym[n]}$: ${_u(m)}^{{*}}$" for (n, _s, m, _o) in fam]
    lines += [r"    composite resonances & " + " & ".join(cells) + r" \\",
              r"    \multicolumn{4}{l}{\footnotesize $^{*}$ predicted, not yet observed"
              r" (rough TeV-scale estimates from the walking bound $M_V\gtrsim13 f_\pi$;"
              r" exact owed to the lattice).} \\",
              r"    \bottomrule", r"  \end{tabular}", r"\end{table}", ""]
    with open(os.path.join(TEX_DIR, "weltformel_table.tex"), "w") as f:
        f.write("\n".join(lines))
    print("wrote", os.path.join(TEX_DIR, "weltformel_table.tex"))

    # ---------- figure ----------
    fig, ax = plt.subplots(figsize=(11.5, 6.2))
    xpos = {"up-quark": 0, "down-quark": 1, "charged-lepton": 2, "neutrino": 3, "boson": 4}
    for t in ("up-quark", "down-quark", "charged-lepton"):
        x = xpos[t]
        for i, (lab, p, o) in enumerate(zip(wf.LABELS[t], mat[t], wf.OBSERVED_GEV[t])):
            dx = (i - 1) * 0.13
            ax.scatter(x + dx, o * 1000, s=120, color=GROUP_COLOR[t], edgecolor="k", lw=0.6,
                       zorder=3)
            ax.scatter(x + dx, p * 1000, s=120, facecolor="white", edgecolor=GROUP_COLOR[t],
                       lw=1.9, zorder=3)
            ax.plot([x + dx, x + dx], [min(p, o) * 1000, max(p, o) * 1000],
                    color=GROUP_COLOR[t], lw=1.0, alpha=0.5, zorder=2)
            ax.annotate(lab, (x + dx, o * 1000), textcoords="offset points", xytext=(0, 9),
                        ha="center", fontsize=8.5, color=GROUP_COLOR[t])
    # neutrinos: predicted -> 0 (off the bottom); show measured floor + arrow
    for i, o in enumerate(wf.OBSERVED_GEV["neutrino"]):
        dx = (i - 1) * 0.13
        ax.scatter(3 + dx, o * 1000, s=90, color=GROUP_COLOR["neutrino"], edgecolor="k",
                   lw=0.5, marker="v", zorder=3)
    ax.annotate("seesaw-suppressed:\nRH singlet $\\Rightarrow m_\\nu\\sim m_D^2/M$\n(sub-eV, not "
                "exactly 0)", (3, 1e-7), textcoords="offset points", xytext=(-4, 6), fontsize=7.5,
                color=GROUP_COLOR["neutrino"], ha="center")
    # bosons
    for k in ("W", "Z", "H"):
        dx = {"W": -0.13, "Z": 0.0, "H": 0.13}[k]
        ax.scatter(4 + dx, wf.OBSERVED_BOSONS[k] * 1000, s=120, color="C1", edgecolor="k",
                   lw=0.6, zorder=3)
        ax.scatter(4 + dx, bm[k] * 1000, s=120, facecolor="white", edgecolor="C1", lw=1.9,
                   zorder=3)
        ax.annotate(k, (4 + dx, wf.OBSERVED_BOSONS[k] * 1000), textcoords="offset points",
                    xytext=(0, 9), ha="center", fontsize=8.5, color="C1")
    # predicted composite family above the Higgs -- not yet observed (open, asterisked)
    sym = {"heavier scalar": "h'$^*$", "vector (techni-rho)": r"$\rho_T^*$",
           "axial-vector (techni-a_1)": "$a_T^*$"}
    for (name, _s, m, found) in wf.composite_resonances():
        if found:
            continue
        ax.scatter(4, m * 1000, s=130, facecolor="white", edgecolor="C1", lw=1.9, marker="D",
                   zorder=3)
        ax.annotate(sym.get(name, "?"), (4, m * 1000), textcoords="offset points",
                    xytext=(12, -3), fontsize=9, color="C1")
    ax.set_yscale("log")
    ax.set_xticks([0, 1, 2, 3, 4])
    ax.set_xticklabels(["up-type\nquarks", "down-type\nquarks", "charged\nleptons",
                        "neutrinos", "$W,Z,H$"])
    ax.set_ylabel("mass (MeV)")
    ax.set_ylim(1e-8, 1e7)
    proxies = [Line2D([0], [0], marker="o", color="w", markerfacecolor="0.3",
                      markeredgecolor="k", markersize=11, label="measured"),
               Line2D([0], [0], marker="o", color="w", markerfacecolor="white",
                      markeredgecolor="0.3", markeredgewidth=1.9, markersize=11,
                      label="torsiton (Weltformel, no fit)"),
               Line2D([0], [0], marker="D", color="w", markerfacecolor="white",
                      markeredgecolor="C1", markeredgewidth=1.9, markersize=10,
                      label="predicted composite family (not yet found)")]
    ax.legend(handles=proxies, fontsize=9.5, loc="center left", bbox_to_anchor=(0.0, 0.30))
    ax.set_title("The Weltformel spectrum: all 15 elementary masses from the equations\n"
                 "one global scale, no fitting -- structure exact, magnitudes within "
                 "1--2 orders, bosons within a percent", fontsize=12)
    ax.grid(True, which="both", axis="y", alpha=0.15)
    fig.tight_layout()
    fig.savefig(os.path.join(PDF_DIR, "weltformel_spectrum.pdf"))
    fig.savefig(os.path.join(PDF_DIR, "weltformel_spectrum.png"), dpi=130)
    plt.close(fig)
    print("wrote", os.path.join(PDF_DIR, "weltformel_spectrum.pdf"))
    print("worst fermion factor:", round(wf.summary()["worst_fermion_factor"], 1),
          " worst boson factor:", round(wf.summary()["worst_boson_factor"], 3))


if __name__ == "__main__":
    main()
