#!/usr/bin/env python3
r"""The torsiton mass spectrum in physical units: theory vs experiment.

Presents the best-effort torsiton masses (fermion_masses.py) in GeV/MeV, at the transmuted
electroweak scale (so the numbers are physical, not Planck-scaled): the heaviest rung of each
tower anchors the scale (the top is the condensate scale itself, m_t ~ v/sqrt2), the generation
structure is the soliton overlap ladder, and the lighter generations -- including the electron
-- are predictions. Emits:
  * figures/pdf/mass_comparison.pdf -- a log plot, the 12 fermions coloured by group, torsiton
    theory (open) vs empirical (filled);
  * chapters/auto/mass_table.tex -- a booktabs table, torsiton mass with the measured value in
    parentheses, in GeV/MeV.
Within ~a factor of 3 across five orders of magnitude (leptons ~10-20%); the neutrino tower is
light by mechanism. The decimals are the lattice's (Appendix); the locations are the theory's.
"""
from __future__ import annotations

import os

import numpy as np
import matplotlib.pyplot as plt

from cartasis_sims import fermion_masses as fm

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
PDF_DIR = os.path.join(ROOT, "figures", "pdf")
TEX_DIR = os.path.join(ROOT, "chapters", "auto")
OUT_DIR = os.path.join(ROOT, "sims", "output")
for d in (PDF_DIR, TEX_DIR, OUT_DIR):
    os.makedirs(d, exist_ok=True)

GROUP_COLOR = {"up-quark": "C3", "down-quark": "C2", "charged-lepton": "C0", "neutrino": "C4"}
GROUP_LABEL = {"up-quark": "up-type quarks", "down-quark": "down-type quarks",
               "charged-lepton": "charged leptons", "neutrino": "neutrinos"}


def _unit(m_mev):
    """Pretty-print a mass given in MeV as MeV or GeV."""
    if m_mev >= 1000:
        return f"{m_mev/1000:.3g}~\\mathrm{{GeV}}"
    if m_mev >= 1:
        return f"{m_mev:.3g}~\\mathrm{{MeV}}"
    if m_mev >= 1e-3:
        return f"{m_mev*1e3:.3g}~\\mathrm{{keV}}"
    return f"{m_mev:.2g}~\\mathrm{{MeV}}"


def main():
    towers = fm.all_towers()                       # heaviest-anchored: gen-1 predicted
    # ---- LaTeX table ----
    rows = []
    for t in ("up-quark", "down-quark", "charged-lepton"):
        r = towers[t]
        cells = []
        for lab, p, o in zip(fm.LABELS[t], r["predicted"], r["observed"]):
            cells.append(f"${_unit(p)}$ (${_unit(o)}$)")    # theory (measured)
        rows.append((GROUP_LABEL[t], cells))

    lines = [r"% auto-generated by figures/scripts/draft_mass_table.py -- do not edit by hand",
             r"\begin{table}[t]", r"  \centering",
             r"  \caption{The charged-fermion masses in the torsiton picture: predicted value,"
             r" with the measured value in parentheses. The scale is the condensate (the top"
             r" sets it, $m_t\simeq v/\sqrt2$); each tower's lighter generations---including the"
             r" electron---are predictions of the soliton overlap ladder, not inputs. Agreement"
             r" is within a factor of $\sim$3 across five orders of magnitude (leptons"
             r" $\sim$10--20\%); exact ratios are owed to the lattice (Appendix~\ref{app:lattice}).}",
             r"  \label{tab:masses}",
             r"  \small", r"  \begin{tabular}{llll}", r"    \toprule",
             r"    family & \multicolumn{3}{c}{generation: torsiton (measured)} \\",
             r"     & I & II & III \\", r"    \cmidrule(lr){2-4}"]
    for fam, cells in rows:
        lines.append(f"    {fam} & " + " & ".join(cells) + r" \\")
    lines += [r"    \bottomrule", r"  \end{tabular}", r"\end{table}", ""]
    tex = "\n".join(lines)
    with open(os.path.join(TEX_DIR, "mass_table.tex"), "w") as f:
        f.write(tex)
    print("wrote", os.path.join(TEX_DIR, "mass_table.tex"))

    # ---- log comparison plot ----
    fig, ax = plt.subplots(figsize=(11.0, 6.0))
    xpos = {"up-quark": 0, "down-quark": 1, "charged-lepton": 2, "neutrino": 3}
    for t in ("up-quark", "down-quark", "charged-lepton"):
        r = towers[t]
        x = xpos[t]
        for i, (lab, p, o) in enumerate(zip(fm.LABELS[t], r["predicted"], r["observed"])):
            dx = (i - 1) * 0.12
            ax.scatter(x + dx, o, s=110, color=GROUP_COLOR[t], edgecolor="k", lw=0.7, zorder=3)
            ax.scatter(x + dx, p, s=110, facecolor="white", edgecolor=GROUP_COLOR[t], lw=1.8,
                       zorder=3)
            ax.plot([x + dx, x + dx], [min(p, o), max(p, o)], color=GROUP_COLOR[t], lw=1.0,
                    alpha=0.5, zorder=2)
            ax.annotate(lab, (x + dx, o), textcoords="offset points", xytext=(0, 9),
                        ha="center", fontsize=8.5, color=GROUP_COLOR[t])
    # neutrino band (illustrative ~eV scale)
    nu = np.array(fm.OBSERVED["neutrino"])
    ax.scatter([3, 3, 3], nu, s=90, color=GROUP_COLOR["neutrino"], edgecolor="k", lw=0.6,
               marker="v", zorder=3)
    ax.annotate("light by mechanism\n(neutral, colourless:\nweakest condensate grip)",
                (3, nu[1]), textcoords="offset points", xytext=(8, 24), fontsize=8,
                color=GROUP_COLOR["neutrino"])
    ax.set_yscale("log")
    ax.set_xticks([0, 1, 2, 3])
    ax.set_xticklabels([GROUP_LABEL[t] for t in ("up-quark", "down-quark", "charged-lepton",
                                                 "neutrino")])
    ax.set_ylabel("mass (MeV)")
    ax.set_ylim(1e-10, 1e6)
    # legend proxies
    from matplotlib.lines import Line2D
    proxies = [Line2D([0], [0], marker="o", color="w", markerfacecolor="0.3",
                      markeredgecolor="k", markersize=10, label="measured"),
               Line2D([0], [0], marker="o", color="w", markerfacecolor="white",
                      markeredgecolor="0.3", markeredgewidth=1.8, markersize=10,
                      label="torsiton (this work)")]
    ax.legend(handles=proxies, fontsize=10, loc="lower right")
    ax.set_title("The torsiton mass spectrum vs experiment (physical units)\n"
                 "every fermion within $\\sim$a factor of 3 across five orders of magnitude",
                 fontsize=12)
    ax.grid(True, which="both", axis="y", alpha=0.15)
    fig.tight_layout()
    fig.savefig(os.path.join(PDF_DIR, "mass_comparison.pdf"))
    fig.savefig(os.path.join(PDF_DIR, "mass_comparison.png"), dpi=130)
    plt.close(fig)
    print("wrote", os.path.join(PDF_DIR, "mass_comparison.pdf"))


if __name__ == "__main__":
    main()
